name: Bug Report
labels: Bug
assignees: Voxel6
description: File a bug report about an occurring problem.
title: "[BUG]: "
body:
  - type: markdown
    attributes:
      value: Thank you for putting in the time to file a bug report!
      
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: Provide clear and concise information about what happened and what the problem may be.
      placeholder: ex. I was jumping around inside my house when all of a sudden I started flying.
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Provide clear and concise information about what you expected to happen.
      placeholder: ex. I expected to continue jumping and landing on the ground, but instead I was floating out of the window.
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Provide steps to reproduce the problem/behavior. If you can't, leave this text box blank.
      placeholder: |
                ex. 
                Steps to Reproduce:
                1. Build a house.
                2. Jump up and down.
                3. Start flying into the air?
    validations:
      required: false
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, provide any screenshots that may help explain or provide info about the problem. If you can't, leave this text box blank.
      placeholder: ex. I have a screenshot of what I was wearing before I started flying and a screenshot of me actively flying.
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: If applicable, provide any relevant log information that may help explain or provide info about the problem. You can either paste your log info into the box below or copy and paste the log file into the "Additional Context" section. For additional help, log files are typically found in your game's "logs" folder. If you can't, leave this text box blank.
      placeholder: |
        ex.
        [11:16:24] [Server thread/INFO]: [Voxel_6: Gave 43 [Spruce Planks] to Voxel_6]
        [11:16:24] [Render thread/INFO]: [System] [CHAT] Gave 43 [Spruce Planks] to Voxel_6
        [11:16:24] [Render thread/INFO]: Loaded 236 advancements
        [11:17:05] [Server thread/INFO]: Voxel_6 was caught by Necromancer's fangs
        [11:17:05] [Render thread/INFO]: [System] [CHAT] Voxel_6 was caught by Necromancer's fangs
        [11:17:07] [Render thread/INFO]: Minimap updated server level id: -2091931884 for world ResourceKey[minecraft:dimension / minecraft:overworld]
        [11:17:07] [Render thread/INFO]: Received config from server
        [11:17:07] [Server thread/INFO]: Client of Voxel_6 accepted server config.
        [11:17:19] [Server thread/INFO]: [Voxel_6: Set own game mode to Creative Mode]
        [11:17:19] [Render thread/INFO]: [System] [CHAT] Set own game mode to Creative Mode
        [11:17:32] [Server thread/INFO]: [Voxel_6: Summoned new Wolf]
        [11:17:32] [Render thread/INFO]: [System] [CHAT] Summoned new Wolf
        [11:17:34] [Server thread/INFO]: [Voxel_6: Summoned new Wolf]
        [11:17:34] [Render thread/INFO]: [System] [CHAT] Summoned new Wolf
        [11:17:37] [Server thread/INFO]: [Voxel_6: Summoned new Wolf]
        [11:17:37] [Render thread/INFO]: [System] [CHAT] Summoned new Wolf
        [11:18:15] [Server thread/INFO]: Voxel_6 has completed the challenge [Cover me in... Wings?]
        [11:18:15] [Render thread/INFO]: [System] [CHAT] Voxel_6 has completed the challenge [Cover me in... Wings?]
        [11:18:15] [Render thread/INFO]: Loaded 243 advancements
        [11:18:26] [Server thread/INFO]: Voxel_6 has reached the goal [Sky's the Limit]
        [11:18:26] [Render thread/INFO]: [System] [CHAT] Voxel_6 has reached the goal [Sky's the Limit]
        [11:18:27] [Render thread/INFO]: Loaded 250 advancements
        [11:18:47] [Server thread/INFO]: [Not Secure] <Voxel_6> woah
        [11:18:47] [Render thread/INFO]: [CHAT] <Voxel_6> woah
        [11:18:58] [Render thread/INFO]: Loaded 281 advancements
        [11:19:18] [Server thread/INFO]: [Not Secure] <Voxel_6> im flying
        [11:19:18] [Render thread/INFO]: [CHAT] <Voxel_6> im flying
        [11:19:21] [Server thread/INFO]: Saving and pausing game...
      render: shell
    validations:
      required: false
      
  - type: dropdown
    id: modpack-version
    attributes:
      label: Modpack Version
      description: Provide the version of the modpack you were using when the problem occurred.
      options:
                - "v3.0.0 Release (latest)"
                - "v2.2.2 Beta"
                - "v2.2.1 Beta"
                - "v2.2.0 Beta"
                - "v2.1.0 Release"
                - "v2.0.2 Release"
                - "v2.0.1 Release"
                - "v2.0.0 Release"
                - "v1.4.1 Beta"
                - "v1.4.0 Beta"
                - "v1.3.0 Beta"
                - "v1.2.3 Beta"
                - "v1.2.2 Beta"
                - "v1.2.1 Beta"
                - "v1.2.0 Beta"
                - "v1.1.1 Beta"
                - "v1.1.0 Beta"
                - "v1.0.0 Beta"
                - "v0.3.0 Alpha"
                - "v0.2.1 Alpha"
                - "v0.2.0 Alpha"
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional context relating to the problem or info that could aid in solving the problem here. If you can't, leave this text box blank.
      placeholder: ex. I was playing in Creative mode when the problem occurred.
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Conditions
      description: By submitting your issue, you agree to the following conditions below.
      options:
        - label: I have searched the issue tracker and confirmed that my issue has not already been reported.
          required: true
        - label: I have verified that, if not using the latest version, my problem hasn't been fixed. I recognize that if my problem has been fixed in a newer version of the modpack, my issue will be closed.
          required: true
        - label: I have verified I have not modified the modpack in any way by adding/removing/changing mods, resource packs, data packs, and/or config files. If I have, this must be mentioned in "Additional Context."
          required: true
