name: Crash Report
labels: Game Crash
assignees: Voxel6
description: File a crash report that has occurred while playing.
title: "[CRASH]: "
body:
  - type: markdown
    attributes:
      value: Thank you for putting in the time to file a crash report!
      
  - type: textarea
    id: logs
    attributes:
      label: Crash Report File & latest.log
      description: Provide any relevant log information that may help explain or provide info about the crash. You can either paste your log info into the box below or copy and paste the crash report and latest.log file into the "Additional Context" section. For additional help, your crash report file can be found in your game's "crash-reports" folder. Your latest.log file is found in your game's "logs" folder. 
      placeholder: |
        ex.
        ---- Minecraft Crash Report ----
        // Hey, that tickles! Hehehe!
        
        Time: 2025-08-09 22:51:01
        Description: Mod loading error has occurred
        
        java.lang.Exception: Mod Loading has failed
        	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.4.0-universal.jar%23789!/:?] {re:classloading}
        	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:135) ~[forge-1.20.1-47.4.0-universal.jar%23789!/:?] {re:classloading}
        	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading}
        	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.4.0-universal.jar%23789!/:?] {re:classloading}
        	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.4.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
        	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.4.0.jar:?] {}
        	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.4.0.jar:?] {}
        	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.4.0.jar:?] {}
        	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
        
        
        A detailed walkthrough of the error, its code path and all known details is as follows:
        ---------------------------------------------------------------------------------------
        
        -- Head --
        Thread: Render thread
        Suspected Mods: NONE
        Stacktrace:
        	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:63) ~[forge-1.20.1-47.4.0-universal.jar%23789!/:?] {re:classloading}
        -- MOD irons_spellbooks --
        Details:
        	Mod File: /C:/Users/jgowe/curseforge/minecraft/Instances/Echoes of the Void/mods/irons_spellbooks-1.20.1-3.4.0.10.jar
        	Failure message: Mod irons_spellbooks requires caelus 3.1.0+1.20 or above
        		Currently, caelus is not installed
        	Mod Version: 1.20.1-3.4.0.10
        	Mod Issue URL: https://github.com/iron431/Irons-Spells-n-Spellbooks/issues
        	Exception message: MISSING EXCEPTION MESSAGE
        Stacktrace:
        	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:63) ~[forge-1.20.1-47.4.0-universal.jar%23789!/:?] {re:classloading}
        	at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {}
        	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:61) ~[forge-1.20.1-47.4.0-universal.jar%23789!/:?] {re:classloading}
        	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:135) ~[forge-1.20.1-47.4.0-universal.jar%23789!/:?] {re:classloading}
        	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading}
        	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.4.0-universal.jar%23789!/:?] {re:classloading}
        	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23784!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.4.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
        	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.4.0.jar:?] {}
        	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.4.0.jar:?] {}
        	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.4.0.jar:?] {}
        	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
        	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
        
        
        -- MOD colytra --
        Details:
        	Mod File: /C:/Users/jgowe/curseforge/minecraft/Instances/Echoes of the Void/mods/colytra-forge-6.2.2+1.20.1.jar
        	Failure message: Mod colytra requires caelus 3.1.0 or above
        		Currently, caelus is not installed
        	Mod Version: 6.2.2+1.20.1
        	Mod Issue URL: https://github.com/illusivesoulworks/colytra/issues
        	Exception message: MISSING EXCEPTION MESSAGE
      render: shell
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Provide steps to reproduce the crash. Make sure your information is clear and concise so we can solve your problem.
      placeholder: |
                ex. Steps to Reproduce:
                1. Create a new world, specifically a superflat world.
                2. Find a village, any village.
                3. Seconds after finding a village, around 10 seconds, the game freezes and crashes.
    validations:
      required: true
      
  - type: dropdown
    id: modpack-version
    attributes:
      label: Modpack Version
      description: Provide the version of the modpack you were using when the problem occurred.
      options:
                - "v3.0.0 Release (latest)"
                - "v2.2.2 Beta"
                - "v2.2.1 Beta"
                - "v2.2.0 Beta"
                - "v2.1.0 Release"
                - "v2.0.2 Release"
                - "v2.0.1 Release"
                - "v2.0.0 Release"
                - "v1.4.1 Beta"
                - "v1.4.0 Beta"
                - "v1.3.0 Beta"
                - "v1.2.3 Beta"
                - "v1.2.2 Beta"
                - "v1.2.1 Beta"
                - "v1.2.0 Beta"
                - "v1.1.1 Beta"
                - "v1.1.0 Beta"
                - "v1.0.0 Beta"
                - "v0.3.0 Alpha"
                - "v0.2.1 Alpha"
                - "v0.2.0 Alpha"
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What is your Operating System? This is optional, but it could help create a solution to your problem.
      placeholder: ex. Windows 11
    validations:
      required: false
      
  - type: input
    id: graphics-processing-unit
    attributes:
      label: GPU
      description: What is your GPU? This is optional, but it could help create a solution to your problem.
      placeholder: ex. NVIDIA GeForce RTX 3090 Ti
    validations:
      required: false

  - type: input
    id: central-processing-unit
    attributes:
      label: CPU
      description: What is your CPU? This is optional, but it could help create a solution to your problem.
      placeholder: ex. Intel Core i9-9900K
    validations:
      required: false
    
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional context relating to the problem here. If you can't, leave this text box blank.
      placeholder: ex. I remember adding a mod that modified how villages loaded.
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Conditions
      description: Check the boxes below to confirm your submission. If a box does not meet your condition, do not check it.
      options:
        - label: I have searched the issue tracker and confirmed that my issue has not already been reported.
          required: true
        - label: I have verified that, if not using the latest version, my problem hasn't been fixed. I recognize that if my problem has been fixed in a newer version of the modpack, my issue will be closed.
          required: true
        - label: I have verified I have not modified the modpack in any way by adding/removing/changing mods, resource packs, data packs, and/or config files. If I have, this must be mentioned in "Additional Context."
          required: true
