name: Feature Request
labels: Enhancement
assignees: Voxel6
description: Suggest an idea for the modpack.
title: "[FEATURE REQUEST]: "
body:
  - type: markdown
    attributes:
      value: Thank you for putting in the time to file a feature request!
      
  - type: textarea
    id: problem-related
    attributes:
      label: Is your feature problem related?
      description: Describe your feature and the problem you have been facing. If you can't, leave this text box blank.
      placeholder: ex. I wanted to suggest airplanes because getting around in the world is annoyingly slow.
    validations:
      required: false
      
  - type: textarea
    id: suggested-feature
    attributes:
      label: What is your suggested feature?
      description: Provide any information that relates to your suggestion or idea.
      placeholder: ex. I wanted to suggest that there could be more village variants to make finding villages more unique.
    validations:
      required: true
      
  - type: textarea
    id: alternative-ideas
    attributes:
      label: Were there any alternative ideas to your feature?
      description: Provide any information that relates to your alternative suggestions or ideas. If you can't, leave this text box blank.
      placeholder: ex. An alternative to my main idea was actually to make villages rarer to make finding them more memorable.
    validations:
      required: false
      
  - type: dropdown
    id: modpack-version
    attributes:
      label: Modpack Version
      description: Provide the version of the modpack you were using before you created this request.
      options:
                - "v3.0.0 Release (latest)"
                - "v2.2.2 Beta"
                - "v2.2.1 Beta"
                - "v2.2.0 Beta"
                - "v2.1.0 Release"
                - "v2.0.2 Release"
                - "v2.0.1 Release"
                - "v2.0.0 Release"
                - "v1.4.1 Beta"
                - "v1.4.0 Beta"
                - "v1.3.0 Beta"
                - "v1.2.3 Beta"
                - "v1.2.2 Beta"
                - "v1.2.1 Beta"
                - "v1.2.0 Beta"
                - "v1.1.1 Beta"
                - "v1.1.0 Beta"
                - "v1.0.0 Beta"
                - "v0.3.0 Alpha"
                - "v0.2.1 Alpha"
                - "v0.2.0 Alpha"
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional context that may be related to suggestions or ideas. If you can't, leave this text box blank.
      placeholder: ex. I only wanted to suggest these ideas as I feel they could make exploration better.
    validations:
      required: false
